on: push
permissions: write-all # Need to find out what the minimum write permissions that are needed
jobs:
  build:
    strategy:
      matrix:
        release: [windows, macos, ubuntu]
    runs-on: ${{ matrix.release }}-latest
    steps:
      - name: Create ${{ matrix.release }} Executable
        uses: sayyid5416/pyinstaller@v1
        with:
          python_ver: '3.11.4'
          spec: './tadpole.py'
          requirements: 'requirements.txt'
          upload_exe_with_name: 'tadpole-${{ matrix.release }}'
          options: --onefile, -F, --icon frog.ico, --clean, --noconsole, --version-file versioninfo,
  release:
      needs: build
      runs-on: ubuntu-latest
      steps:
        - uses: actions/download-artifact@v2.1.1
          id: dl-ubuntu
          with:
              name: tadpole-ubuntu
              path: output/linux
        - uses: actions/download-artifact@v2.1.1
          id: dl-windows
          with:
              name: tadpole-windows
              path: output/windows
        - uses: actions/download-artifact@v2.1.1
          id: dl-macos
          with:
              name: tadpole-macos
              path: output/macos
        - run: tree "/home/runner/work/tadpole-workflow/tadpole-workflow/output/"
        - uses: softprops/action-gh-release@v1
          with:
            draft: true
            files: |
               ${{steps.dl-ubuntu.outputs.download-path}}/tadpole-ubuntu
               ${{steps.dl-windows.outputs.download-path}}/tadpole-windows
               ${{steps.dl-macos.outputs.download-path}}/tadpole-macos
