on: push
jobs:
  pyinstaller-build-windows:
    runs-on: windows-latest
    steps:
      - name: Create Executable
        uses: sayyid5416/pyinstaller@v1
        with:
          python_ver: '3.6'
          requirements: 'requirements.txt'
          upload_exe_with_name: 'tadpole-windows'
          options: --onefile, -F, --icon frog.ico, --clean, --noconsole, --version-file versioninfo,
  pyinstaller-build-macos:
    runs-on: macos-latest
    steps:
      - name: Create MacOS Executable
        uses: sayyid5416/pyinstaller@v1
        with:
          python_ver: '3.6'
          requirements: 'requirements.txt'
          upload_exe_with_name: 'tadpole-windows'
          options: --onefile, -F, --icon frog.ico, --clean, --noconsole, --version-file versioninfo,
  pyinstaller-build-linux:
    runs-on: ubuntu-latest
    steps:
      - name: Create Linux Executable
        uses: sayyid5416/pyinstaller@v1
        with:
          python_ver: '3.6'
          requirements: 'requirements.txt'
          upload_exe_with_name: 'tadpole-windows'
          options: --onefile, -F, --icon frog.ico, --clean, --noconsole, --version-file versioninfo,
