on: push
jobs:
  create-requirementstxt:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      - name: Self test # Is this needed?
        id: selftest # Is this needed?
        uses: ryan-rozario/pipreqs-action-cpy@master
        with:
          PROJECT_PATH: .   # the root of the repository
          REQUIREMENT_PATH: ./requirements.txt  # create the requirement.txt in the root of the repository 
  pyinstaller-build-windows:
    runs-on: windows-latest
    steps:
      - name: Create Windows Executable
        uses: sayyid5416/pyinstaller@v1
        with:
          python_ver: '3.11.4'
          requirements: 'requirements.txt'
          upload_exe_with_name: 'tadpole-windows'
          options: --onefile, -F, --icon frog.ico, --clean, --noconsole, --version-file versioninfo,
  pyinstaller-build-macos:
    runs-on: macos-latest
    steps:
      - name: Create MacOS Executable
        uses: sayyid5416/pyinstaller@v1
        with:
          python_ver: '3.11.4'
          requirements: 'requirements.txt'
          upload_exe_with_name: 'tadpole-macos'
          options: --onefile, -F, --icon frog.ico, --clean, --noconsole, --version-file versioninfo,
  pyinstaller-build-linux:
    runs-on: ubuntu-latest
    steps:
      - name: Create Linux Executable
        uses: sayyid5416/pyinstaller@v1
        with:
          python_ver: '3.11.4'
          requirements: 'requirements.txt'
          upload_exe_with_name: 'tadpole-linux'
          options: --onefile, -F, --icon frog.ico, --clean, --noconsole, --version-file versioninfo,
